### ISSUE TITLE
Compile error:

### ISSUE THREAD

**Issue by zhangfq-chemistry** [clibequilibrium/EquilibriumEngine#2]
EquilibriumEngine/3rdparty/bgfx/bgfx/src/dxgi.h:9:10: fatal error: sal.h No such a file

**Comment by clibequilibrium** [comment]
Hello @zhangfq-chemistry 

Make sure you have build tools installed. 

![image](https://user-images.githubusercontent.com/105135724/196178977-079cfbfa-b514-441e-9210-69903eaa3983.png)

![image](https://user-images.githubusercontent.com/105135724/196179023-f447c60c-da68-4483-81de-bddf06c2ca67.png)
