### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by Tymofii-Lytvynenko** [clibequilibrium/EquilibriumEngine#5]
No updates planned? How ready is the project for production?

**Comment by clibequilibrium** [comment]
HI, thanks for your message.

I do not have any plans to update the engine but happy to assist anybody in their journey. 

#### As for being production ready. 
It depends what you consider "ready for production". If lack of cross platform, proper asset system, animation system, physics system, audio system is something you consider, then for sure it is not ready for production. If you or your studio tries to evaluate the engines out there just go with Unreal, Unity or Godot. Unigine for enterprise. 

Equilibrium Engine always meant to be an example of how to create a barebone ECS engine with flecs and bgfx entirely in C with hot reloading. So treat is more as educational, starter base for people to get acquired with ECS, flecs and bgfx, or even development in C. There is a similar C# port that shows how to do it but with Arch ECS library https://github.com/clibequilibrium/EquilibriumEngine-CSharp. 

Equilibrium Engine borrows module design from flecs making the engine easily modifiable and extendable.
